site_name: Transformers rest API documentation
site_description: Documentation for the Transformers REST API
site_author: Hugging Face

theme:
  name: material
  logo: img/logo.png
  language: es

nav:
  - Home: index.md
  - Guia:
      - Quickstart: guia/quickstart.md
      - Authentication: guia/authentication.md
      - Rate Limits: guia/rate_limits.md
  - ReferenceAPI:
      - Overview: referenceAPI/overview.md
      - Endpoints: referenceAPI/endpoints.md

markdown_extensions:
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: "#"
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true